install:
    script: |
        echo Entering install phase
        sudo rm -rf /spaceduck/*
        aws s3 cp s3://{bucketName}/{filePath}.zip /spaceduck/code.zip
        unzip /spaceduck/code.zip -d /spaceduck/code

        sudo mkdir -p /spaceduck/logs

        sudo npm install -g pm2
        pm2 kill

        sudo kill -9 `sudo lsof -t -i:5000`
        sudo kill -9 `sudo lsof -t -i:5001`
        sudo kill -9 `sudo lsof -t -i:5006`
        sudo kill -9 `sudo lsof -t -i:5007`

        echo Install phase complete

build:
    script: |
        echo Entering build phase

        echo Building UserService
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.UserService
        # sudo dotnet publish -o /spaceduck/out/bin/SpaceDuck.UserService -v n
        sudo dotnet build
        echo Build complete

        echo Building Chess
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.ChessGame
        # sudo dotnet publish -o /spaceduck/out/bin/SpaceDuck.ChessGame -v n
        sudo dotnet build
        echo Build complete

        echo Installing UserService frontend
        sudo npm install --prefix /spaceduck/out /spaceduck/code/SpaceDuckFrontend/spaceduck/ --loglevel verbose
        echo UserService frontend installed
        echo Installing Chess frontend
        sudo npm install --prefix /spaceduck/out /spaceduck/code/SpaceDuckFrontend/szachy/ --loglevel verbose
        echo Chess frontend installed
        echo Build phase complete

test:
    script: |
        echo Entering test phase
        echo Test phase complete

deploy:
    script: |
        echo Entering deploy phase
        

        echo Starting UserService backend
        # sudo sh -c 'nohup dotnet /spaceduck/out/bin/SpaceDuck.UserService/SpaceDuck.UserService.dll > /spaceduck/logs/userservice.log 2>&1 &'
        sudo sh -c 'nohup dotnet /spaceduck/code/SpaceDuck.UserService/SpaceDuck.UserService/bin/Debug/netcoreapp3.1/SpaceDuck.UserService.dll > /spaceduck/logs/userservice.log 2>&1 &'
        echo UserService started

        echo Starting Chess backend
        # sudo sh -c 'nohup dotnet /spaceduck/out/bin/SpaceDuck.ChessGame/SpaceDuck.ChessGame.dll > /spaceduck/logs/chess.log 2>&1 &'
        sudo sh -c 'nohup dotnet /spaceduck/code/SpaceDuck.UserService/SpaceDuck.ChessGame/bin/Debug/netcoreapp3.1/SpaceDuck.ChessGame.dll > /spaceduck/logs/chess.log 2>&1 &'
        echo Chess started

        echo Starting UserService frontend
        pm2 start npm --name "spaceduck" -- start --prefix /spaceduck/out/node_modules/spaceduck
        echo UserService started
        
        echo Starting Chess frontend
        pm2 start npm --name "chess" -- start --prefix /spaceduck/out/node_modules/szachy
        echo Chess started

        echo Deploy phase complete