install:
    script: |
        sudo rm -rf /spaceduck/*
        aws s3 cp s3://{bucketName}/{filePath}.zip /spaceduck/code.zip
        unzip /spaceduck/code.zip -d /spaceduck/code
build:
    script: |
        echo Entering build phase
        export DOTNET_CLI_HOME="/home/ubuntu"
        sudo dotnet clean -c Release -o /spaceduck/bin/SpaceDuck.UserService
        sudo dotnet build /spaceduck/code/SpaceDuck.UserService -c Release -o /spaceduck/bin/SpaceDuck.UserService
        echo Build complete

test:
    script: |
        echo Entering test phase
        echo Test phase complete

deploy:
    script: |
        echo Entering deploy phase
        sudo kill -9 `sudo lsof -t -i:5000`
        sudo kill -9 `sudo lsof -t -i:5001`
        nohup dotnet /spaceduck/bin/SpaceDuck.UserService/SpaceDuck.UserService.dll > /dev/null 2>&1 &
        echo Deploy complete
